Update _element.py
serhatbolsu/robotframework-appiumlibrary pull request #228
Opened 2018-08-30 09:20 UTC by daisyzou

add is_element_exist、get_element_enabled、is_element_visible、is_page_contain_text、get_text_selected、get_name

2018-08-30 09:30 UTC, linyan0321 commented
update name->element.name

2022-12-27 06:07 UTC, serhatbolsu requested changes

2022-12-27 06:07 UTC, serhatbolsu commented on AppiumLibrary/keywords/_element.py
> +        """add Get that element with locator is existed.
remove the "add" in front of keyword documentation please

2022-12-27 06:07 UTC, serhatbolsu commented on AppiumLibrary/keywords/_element.py
> +        """add  Get text with locator is selected.
can you explain what does this do exactly? what is `is_selected()`

2022-12-27 06:07 UTC, serhatbolsu commented on AppiumLibrary/keywords/_element.py
> +        """add Get that element with locator is existed.
same for each keyword

2025-07-12 02:24 UTC, emanlove commented
This complicates and adds several unnecessary keywords. Closing as will not implement.

2025-07-12 02:24 UTC, closed without merging